import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { montserrat } from './fonts'
import Footer from '@/components/shared/Footer'
import Navbar from '@/components/shared/Navbar'
import Divider from '@/components/shared/Divider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar/>
        {children}
        <Divider inverted/>
        <Footer/>
      </body>
    </html>
  )
}
