import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { montserrat } from './fonts'
import Footer from '@/components/shared/Footer'
import Navbar from '@/components/shared/Navbar'
import Divider from '@/components/shared/Divider'
import Slide from '@/components/animations/Slide'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Slide 
          className='hidden lg:block'
          value={50}
          verticalDirection='down'
        >
          <Divider />
        </Slide>
        <Navbar/>
        {children}
        <Divider inverted/>
        <Footer/>
      </body>
    </html>
  )
}
